-- Restore Mohaan Web CMS schema
-- Production database is missing the tables required by the existing API.

create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text,
    description text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create unique index if not exists categories_slug_idx
on public.categories(slug)
where slug is not null;

create table if not exists public.articles (
    id bigint generated by default as identity primary key,
    title text not null,
    slug text,
    excerpt text,
    content text,
    image_url text,
    category_id bigint,
    author text,
    published boolean default false,
    featured boolean default false,
    published_at timestamptz,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create unique index if not exists articles_slug_idx
on public.articles(slug)
where slug is not null;

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text,
    description text,
    price numeric default 0,
    image_url text,
    category_id bigint,
    product_url text,
    gumroad_url text,
    featured boolean default false,
    published boolean default true,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create unique index if not exists products_slug_idx
on public.products(slug)
where slug is not null;

create table if not exists public.site_settings (
    id bigint generated by default as identity primary key,
    key text,
    value text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create unique index if not exists site_settings_key_idx
on public.site_settings(key)
where key is not null;

create table if not exists public.nav_items (
    id bigint generated by default as identity primary key,
    label text not null,
    href text,
    url text,
    sort_order integer default 0,
    visible boolean default true,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists public.home_sections (
    id bigint generated by default as identity primary key,
    name text,
    title text,
    subtitle text,
    content text,
    image_url text,
    section_type text,
    sort_order integer default 0,
    visible boolean default true,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists public.contact_messages (
    id bigint generated by default as identity primary key,
    name text,
    email text,
    subject text,
    message text,
    created_at timestamptz default now()
);

create table if not exists public.media (
    id bigint generated by default as identity primary key,
    url text not null,
    name text,
    type text,
    size bigint,
    created_at timestamptz default now()
);

create table if not exists public.seo_meta (
    id bigint generated by default as identity primary key,
    page text,
    title text,
    description text,
    keywords text,
    canonical_url text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create unique index if not exists seo_meta_page_idx
on public.seo_meta(page)
where page is not null;

-- Refresh PostgREST schema cache
notify pgrst, 'reload schema';
